version: "3"

services: 
  valheim-server-live: 
    image: lloesche/valheim-server
    cap_add:
      - sys_nice
    volumes: 
      - ./config-live:/config
      - ./data-live:/opt/valheim
    ports: 
      - "2456-2458:2456-2458/udp"
      - "9001:9001/tcp"
    env_file:
      - ./.valheim-live.env
    restart: always
    stop_grace_period: 2m
    depends_on: 
      - valheim-bot-live

  valheim-bot-live:
    image: docker.pkg.github.com/eliasase/valheim-discord-bot/valheim-discord-bot:0.1
    ports: 
      - "514:514/udp"
      - "514:514/tcp"
    env_file:
      - ./.valheim-live.env
    environment: 
      - DISCORD__TOKEN=${DISCORD__TOKEN}
      - DISCORD__LOGCHANNEL=valheim
  
    restart: always
    stop_grace_period: 2m  
